### ISSUE TITLE
need ways to introduce k8s

### ISSUE THREAD

**Issue by jainvipin** [contiv/ansible#9]
The roles and groups that are defined so far includes swarm scheduler. What would be the best way to contribute to this repo to add k8s scheduler. Few options I can think of:
- create host-groups that are different for k8s, for example host-group service-master, can be split into two 'service-master-docker' vs 'service-master-k8s'
- abstract out scheduler role from this to be called 'scheduler' and replace it with swarm, k8s, etc.

My preference would be first one (different host-groups) because there may be more dependent top level roles that some of the schedulers (e.g. mesos) might require.

ping @mapuri, @erikh, @jojimt

**Comment by mapuri** [comment]
> abstract out scheduler role from this to be called 'scheduler' and replace it with swarm, k8s, etc.

I think this way works better given our current playbook organization, as host-groups are not per deployment but per project.

We can also do something in the middle which I prefer i.e. have a role for swarm, k8s, mesos and so on. And run them conditionally using ansible variables, something like this:

```
service-master:
- hosts: service-master
  sudo: true
  environment: env
  roles:
...
  - { role: docker }
  - { role: swarm, when: cluster_scheduler == "swarm" }
  - { role: k8s, when: cluster_scheduler == "k8s" }
  - { role: mesos, when: cluster_scheduler == "mesos" }
...
```

And the above playbook can now be run to bring up a Kubernetes cluster by doing something like this:

```
ansible-playbook -i 'inventory-file' -e '{"cluster_scheduler": "k8s"}' ./site.yml
```
